export type QuoteCategory = {
  id: string;
  label: string;
};

export type QuoteTemplateItem = {
  id: string;
  categoryId: string;
  name: string;
  unit: string;
  pricingBasis: string;
  defaultUnitPrice: number;
  defaultQuantity: number;
  description: string;
};

export const quoteCategories: QuoteCategory[] = [
  { id: "preparation", label: "保護與拆除" },
  { id: "electrical", label: "水電工程" },
  { id: "masonry", label: "泥作與防水" },
  { id: "finish", label: "表面與天花" },
  { id: "cabinet", label: "櫃體與木作" },
  { id: "smart-home", label: "智能家居" },
];

export const quoteTemplateItems: QuoteTemplateItem[] = [
  {
    id: "protection-basic",
    categoryId: "preparation",
    name: "基礎保護工程",
    unit: "式",
    pricingBasis: "依案場規模與公共區保護範圍計",
    defaultUnitPrice: 12000,
    defaultQuantity: 1,
    description: "施工前地坪、電梯與公共區保護。",
  },
  {
    id: "demolition-basic",
    categoryId: "preparation",
    name: "拆除清運",
    unit: "式",
    pricingBasis: "依拆除範圍與清運量計",
    defaultUnitPrice: 25000,
    defaultQuantity: 1,
    description: "含基礎拆除與清運費用。",
  },
  {
    id: "waste-bag",
    categoryId: "preparation",
    name: "垃圾清運袋裝",
    unit: "車",
    pricingBasis: "依垃圾量與清運次數計",
    defaultUnitPrice: 8000,
    defaultQuantity: 1,
    description: "適用額外拆除廢棄物與二次清運。",
  },
  {
    id: "electrical-circuit",
    categoryId: "electrical",
    name: "新增迴路",
    unit: "迴路",
    pricingBasis: "依配電箱延伸與線路距離計",
    defaultUnitPrice: 4800,
    defaultQuantity: 1,
    description: "新增配電回路與線材整理。",
  },
  {
    id: "electrical-outlet",
    categoryId: "electrical",
    name: "新增插座",
    unit: "處",
    pricingBasis: "一般插座點位單價",
    defaultUnitPrice: 1200,
    defaultQuantity: 1,
    description: "新增一般插座點位。",
  },
  {
    id: "electrical-switch-move",
    categoryId: "electrical",
    name: "開關移位",
    unit: "處",
    pricingBasis: "含配線延伸與牆面修補",
    defaultUnitPrice: 900,
    defaultQuantity: 1,
    description: "含原開關位移與基礎整理。",
  },
  {
    id: "lighting-downlight",
    categoryId: "electrical",
    name: "崁燈安裝",
    unit: "盞",
    pricingBasis: "含基本配線與安裝工資",
    defaultUnitPrice: 1800,
    defaultQuantity: 1,
    description: "含線路配置與燈具安裝。",
  },
  {
    id: "weak-current",
    categoryId: "electrical",
    name: "弱電 / 網路點位",
    unit: "點",
    pricingBasis: "依每一點佈線與面板安裝計",
    defaultUnitPrice: 1800,
    defaultQuantity: 1,
    description: "適用網路、電視與監視器預留點位。",
  },
  {
    id: "water-piping",
    categoryId: "electrical",
    name: "冷熱水配管更新",
    unit: "式",
    pricingBasis: "依更新範圍與點位數量計",
    defaultUnitPrice: 18000,
    defaultQuantity: 1,
    description: "適用廚房、衛浴或局部冷熱水路更新。",
  },
  {
    id: "bathroom-waterproof",
    categoryId: "masonry",
    name: "浴室防水更新",
    unit: "間",
    pricingBasis: "依每間衛浴防水範圍計",
    defaultUnitPrice: 28000,
    defaultQuantity: 1,
    description: "含基礎防水層施作。",
  },
  {
    id: "tiling-refresh",
    categoryId: "masonry",
    name: "牆地磚更新",
    unit: "坪",
    pricingBasis: "依貼磚面積與磁磚規格計",
    defaultUnitPrice: 4800,
    defaultQuantity: 1,
    description: "含貼磚工資與基礎材料。",
  },
  {
    id: "drainage-relocation",
    categoryId: "masonry",
    name: "排水移位",
    unit: "處",
    pricingBasis: "依移位距離與地坪開挖難度計",
    defaultUnitPrice: 6500,
    defaultQuantity: 1,
    description: "常用於廚房、衛浴設備位置調整。",
  },
  {
    id: "ceiling-flat",
    categoryId: "finish",
    name: "平釘天花",
    unit: "坪",
    pricingBasis: "依天花面積與收邊複雜度計",
    defaultUnitPrice: 3200,
    defaultQuantity: 1,
    description: "含角材、板材與批土處理。",
  },
  {
    id: "painting-full",
    categoryId: "finish",
    name: "全室油漆",
    unit: "坪",
    pricingBasis: "依油漆面積與牆況修補量計",
    defaultUnitPrice: 2200,
    defaultQuantity: 1,
    description: "含批土、打磨與面漆。",
  },
  {
    id: "floor-spc",
    categoryId: "finish",
    name: "SPC 地板",
    unit: "坪",
    pricingBasis: "依鋪設面積與現場整平需求計",
    defaultUnitPrice: 3800,
    defaultQuantity: 1,
    description: "含地坪整平與基礎收邊。",
  },
  {
    id: "glass-partition",
    categoryId: "finish",
    name: "玻璃隔間 / 拉門",
    unit: "式",
    pricingBasis: "依玻璃尺寸與五金等級計",
    defaultUnitPrice: 32000,
    defaultQuantity: 1,
    description: "適用書房、浴室或彈性隔間。",
  },
  {
    id: "system-cabinet",
    categoryId: "cabinet",
    name: "系統櫃",
    unit: "尺",
    pricingBasis: "依每尺櫃體長度與五金配置計",
    defaultUnitPrice: 8500,
    defaultQuantity: 1,
    description: "含板材、五金與安裝。",
  },
  {
    id: "woodwork-cabinet",
    categoryId: "cabinet",
    name: "木作收納櫃",
    unit: "尺",
    pricingBasis: "依每尺櫃體長度與表面材質計",
    defaultUnitPrice: 12000,
    defaultQuantity: 1,
    description: "含木作結構、表面處理與安裝。",
  },
  {
    id: "tv-wall",
    categoryId: "cabinet",
    name: "電視牆立面",
    unit: "式",
    pricingBasis: "依立面尺寸與材質做法計",
    defaultUnitPrice: 38000,
    defaultQuantity: 1,
    description: "含立面包覆與細部收邊。",
  },
  {
    id: "entry-cabinet",
    categoryId: "cabinet",
    name: "玄關鞋櫃",
    unit: "式",
    pricingBasis: "依櫃體尺寸、門片與五金配置計",
    defaultUnitPrice: 26000,
    defaultQuantity: 1,
    description: "含鞋櫃、吊衣區或落塵區整合。",
  },
  {
    id: "smart-home-basic",
    categoryId: "smart-home",
    name: "智能家居基礎整合",
    unit: "式",
    pricingBasis: "依整合設備數量與控制情境計",
    defaultUnitPrice: 48000,
    defaultQuantity: 1,
    description: "含燈光、窗簾與空調基礎整合。",
  },
  {
    id: "smart-home-security",
    categoryId: "smart-home",
    name: "門鎖 / 感測 / 監控整合",
    unit: "式",
    pricingBasis: "依設備品牌、數量與串接需求計",
    defaultUnitPrice: 36000,
    defaultQuantity: 1,
    description: "適用智慧門鎖、感測器與監視器整合。",
  },
];

export const quoteDefaultTerms = [
  "本報價為現階段初估，實際金額仍會依現場丈量、材料確認與施工條件微調。",
  "未列項目、特殊保護、特殊搬運、額外加班與大樓管委會相關費用，將另行說明。",
  "若後續有新增工項、材料升級或施工條件變動，會先提供調整內容再確認。",
  "正式開工前會再提供最終版報價與施工安排。",
];

export const quoteInvoiceNotice = {
  title: "稅務與開立發票說明",
  paragraphs: [
    "本工作室目前為個人承攬型態，為替業主節省非必要之稅務管銷成本，本報價單所列金額皆為未稅現金價。完工後將開立具備負責人身分證字號之個人勞務報酬收據，作為合法付款證明。",
    "若業主因報帳需求，確實需要開立統一發票，本工作室可協助委託合作之建材商或工班代為開立。惟依稅法規定，需另行加收 8% 之營業稅與代辦手續費。此稅額費用不包含於本報價單總價內，將於簽約時另行計算。",
  ],
};
